### ISSUE TITLE
Make unfocused tabs even easier to read

### ISSUE THREAD

**Issue by mstenemo** [perragnar/light-plus-tweaked#1]
I would like to be able to make the unfocused tabs (in the onfocused group) even easier to read. The unfocused tabs in the focused group are quite readable already, and I would like all tabs to be this readable. 

Related to this, it would be good if the orange underlining could change color for the different groups. 
The image below shows that "untitled-1" to the left and untitled-3 to the right are not as easy to read. 
![image](https://user-images.githubusercontent.com/4462991/38917851-39f411b6-42ec-11e8-97cf-bc3aed178352.png)

This is a very minor request, as readability is already improved by this extension.

**Comment by perragnar** [comment]
I made the unfocused panel tab text darker and changed the color on unfocused panel active tab border. I'm not sure it's a good thing to make different color for the borders though. What do you think?

![untitled-4](https://user-images.githubusercontent.com/1774047/38933772-3b69102c-431a-11e8-9bb6-aa962422cd73.png)

**Comment by mstenemo** [comment]
that looks great, even easier to read now, thank you for updating!

**Comment by perragnar** [comment]
Great! I will publish the changes to the marketplace.
