### ISSUE TITLE
Put borders around search fields to enhance contrast

### ISSUE THREAD

**Issue by phgmacedo** [perragnar/light-plus-tweaked#10]
I'm having trouble differentiating the search fields in the screenshot: 

![l1](https://user-images.githubusercontent.com/2473545/98305873-7058de00-1fa1-11eb-878f-58b628de2449.png)

The github light theme, for example, puts some sort of border around these fields to make them easier to see: 

![l2](https://user-images.githubusercontent.com/2473545/98305935-89fa2580-1fa1-11eb-894e-40f219c6bdfb.png)

Is there a way to implement this on the theme?

**Comment by perragnar** [comment]
I have added input borders and published an update on the Marketplace. Thanks for the feedback and let me know if there is anything else that could improve the theme.

**Comment by phgmacedo** [comment]
Awesome! Thanks!
