### ISSUE TITLE
[Bug] Text input predictor color and highlight color are the same

### ISSUE THREAD

**Issue by proninyaroslav** [perragnar/light-plus-tweaked#13]
I found this in the latest Light+ Tweaked and VSCode 1.57.0:

![ezgif-6-dcd015da492c](https://user-images.githubusercontent.com/7840559/121917819-23f72d00-cd3e-11eb-9b05-a249519c6d0e.gif)

**Comment by proninyaroslav** [comment]
This can also be seen in the Command Palette:

![command_palette](https://user-images.githubusercontent.com/7840559/121919094-58b7b400-cd3f-11eb-9e46-3083240d8564.png)

**Comment by proninyaroslav** [comment]
In the default Light+ theme, the text predict color looks like this:

![Снимок экрана от 2021-06-14 18-36-41](https://user-images.githubusercontent.com/7840559/121919400-a92f1180-cd3f-11eb-85a5-9023ccc69041.png)

**Comment by perragnar** [comment]
I have fixed this and will publish it to the marketplace. Sorry for the delay tho. 😇 
Thanks @proninyaroslav !

**Comment by perragnar** [comment]
I just realized i have to fix `editorSuggestWidget.focusHighlightForeground` as well. I'm uploading to marketplace right now.
