### ISSUE TITLE
unreadable text in the status bar

### ISSUE THREAD

**Issue by isheebo** [perragnar/light-plus-tweaked#2]
Thanks for the good work @perragnar. Text in the status bar is barely readable in cases where a required tool e.g. eslint  is misconfigured, or when the tests fail for the case of Python. A much more readable color could solve this. 

With [Go](https://golang.org) when `Analysis Tools` are Missing

<img width="1437" alt="screen shot 2018-07-02 at 8 15 34 pm" src="https://user-images.githubusercontent.com/29917291/42177246-b97312e2-7e34-11e8-8e44-f11695e7d73d.png">

With [Python](https://www.python.org) after running tests in the VS Code by clicking the `Run Tests⚡️`  in the status bar.

<img width="709" alt="screen shot 2018-07-02 at 8 05 39 pm" src="https://user-images.githubusercontent.com/29917291/42176928-576be836-7e33-11e8-959f-bfa2b8342e27.png">

With missing `Eslint here`,
<img width="484" alt="screen shot 2018-07-02 at 8 12 57 pm" src="https://user-images.githubusercontent.com/29917291/42177152-6a068a04-7e34-11e8-8e9c-2c49961fc8f1.png">

**Comment by perragnar** [comment]
There's a theme setting for prominent statusbar items which I haven't set. A fix is coming up during the day. Thanks for the feedback!

**Comment by perragnar** [comment]
A new version is out on the marketplace. Is the color OK or should it be more subtle?

**Comment by isheebo** [comment]
Thanks for reaching out @perragnar. On my end, I've updated the extension to the latest version i.e. `0.1.10`. I believe making the color more subtle could do the magic. Thank you

**Comment by perragnar** [comment]
How about making the regular status bar text dark gray and the prominent ones black?

**Comment by perragnar** [comment]
Oh, thats the background color, not the text color! I didn't realize.
I'm not sure the setting `statusBarItem.prominentBackground` is the right one then.

Can you try to add the following to your local settings in VSCode?

```json
"workbench.colorCustomizations": {
    "statusBarItem.prominentBackground": "#00000000",
    "statusBarItem.prominentHoverBackground": "#dddddd"
},
```

Does the yellow text change at all like the __Tab move focus__ item in the screenshots below?

![01](https://user-images.githubusercontent.com/1774047/42502994-c0df05aa-8437-11e8-9cbd-080da4695869.png)
![02](https://user-images.githubusercontent.com/1774047/42502995-c0fabd86-8437-11e8-9094-3b47e1b8d52d.png)

**Comment by perragnar** [comment]
I tweaked the colors a bit and published a new version to the marketplace. Thanks again for helping out!
