### ISSUE TITLE
Line highlighting 

### ISSUE THREAD

**Issue by matkateresa** [perragnar/light-plus-tweaked#3]
Is there an option to change it back to Light+ default line highlighting ?
![dd](https://user-images.githubusercontent.com/35968924/47289525-87674600-d5fb-11e8-91ee-ab6bdbee9851.png)

first one is currently implemented in your theme and id like to use the 2nd one instead

**Comment by perragnar** [comment]
I don't use line highlighting myself. Is lines better than a background color (any color, not just the pale yellow used in my theme)?

**Comment by perragnar** [comment]
I have changed the line highlight to the default style. Thanks for the feedback! 😄
