### ISSUE TITLE
I got a few Tweaked things about your Light+ Tweaked color configuration!

### ISSUE THREAD

**Issue by achuanya** [perragnar/light-plus-tweaked#4]
The Light+ Tweaked color configuration you've done is pretty good, and I like it very much, but what's missing is that when I write projects in PHP, the string color such as "= > < $[] () {} "gets Tweaked in most of its major tweaks. As most of the code Tweaked in most of its major tweaks, it looks like an Tweaked color.Where does it change?

**Comment by achuanya** [comment]
> The Light+ Tweaked color configuration you've done is pretty good, and I like it very much, but what's missing is that when I write projects in PHP, the string color such as "= > < $[] () {} "gets Tweaked in most of its major tweaks. As most of the code Tweaked in most of its major tweaks, it looks like an Tweaked color.Where does it change?

**Comment by achuanya** [comment]
> 你做的Light + Tweaked颜色配置非常好，我非常喜欢它，但缺少的是当我用PHP编写项目时，字符串颜色如“=> <$ []（）{}”得到调整了大部分主要调整。由于大多数代码在大多数主要调整中都被调整，它看起来像一个调整颜色。它会改变吗？

**Comment by achuanya** [comment]
I want to change the colors of the symbols "= > < $[] () {} ". Where are they?

**Comment by perragnar** [comment]
Hey! I will take a look at changing the symbol colors.

**Comment by achuanya** [comment]
@perragnar 好的,麻烦您等你找到" 改变 “=> <$ []（）{}” 符号的颜色语句后告诉回复我一下!

**Comment by achuanya** [comment]
@perragnar Ok, please let me know after you find the color statement of "change" => <$[] () {} "symbol.

**Comment by achuanya** [comment]
I have modified it according to the style format you gave me! Thank you very much!

**Comment by perragnar** [comment]
I hope you got i the way you wanted. 😄
