### ISSUE TITLE
Terminal "ansiBrightYellow" has very poor readability

### ISSUE THREAD

**Issue by pedrogarcia** [perragnar/light-plus-tweaked#5]
The terminal color `terminal.ansiBrightYellow` has very poor readability. It is the default terminal font color on windows. While the description calls it `Bright Yellow`, perhaps it could be of some other color?

![vsode_bright_yellow_light_theme](https://user-images.githubusercontent.com/2473545/52904691-b04cc000-3216-11e9-8f05-9bee66a5a9c3.jpg)

![vsode_bright_yellow_dark_theme](https://user-images.githubusercontent.com/2473545/52904690-adea6600-3216-11e9-9d4d-f20927c3ba69.jpg)

![terminal_yellow](https://user-images.githubusercontent.com/2473545/52904688-a925b200-3216-11e9-9d12-02636b71ea11.jpg)

**Comment by perragnar** [comment]
I totally agree. Yellow text on white background is poor readability. The only yellowish element used in the theme is a rather dark and muted color (see the first image below). Or maybe a slightly lighter but still muted yellow could work (second image). A slightly more orange color could also work..
What do you think?

Colors used:
#795e26
#c9a943

<img width="832" alt="screenshot 2019-02-18 at 20 02 36" src="https://user-images.githubusercontent.com/1774047/52971739-e4f87d00-33b8-11e9-9141-918c5e6d2e30.png">
<img width="832" alt="screenshot 2019-02-18 at 20 07 07" src="https://user-images.githubusercontent.com/1774047/52971751-ea55c780-33b8-11e9-8f62-279bdc94f8af.png">

**Comment by pedrogarcia** [comment]
> #795e26

This is much better. Maybe even a little bit darker?

**Comment by perragnar** [comment]
OK.. Let's try #795e26 since it's a color already in the theme palette. I have published an update to the marketplace with the color change. Give it a try and let me know if it works or not.

Thanks for making the theme better. Cheers!
