### ISSUE TITLE
Improve color for the Remote Development extension status bar button

### ISSUE THREAD

**Issue by pedrogarcia** [perragnar/light-plus-tweaked#8]
The [Remote Development ](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.vscode-remote-extensionpack )extensions add a little blue icon to the status bar, which is quite different from the other status bar icons. 

It looks like this:
![blue](https://user-images.githubusercontent.com/2473545/66421184-c8f42b00-e9dd-11e9-9776-9d9c5880bf44.png)

Can this theme support the extensions a little better?

I used     `"statusBarItem.remoteForeground": "#444444",`  and `"statusBarItem.remoteBackground": "#00000000",` which seems to be more consistent with this theme colors, but maybe they could be a little bit greyer ([as some other themes do](https://github.com/microsoft/vscode/blob/master/extensions/theme-solarized-light/themes/solarized-light-color-theme.json#L449))

My suggestion:
![suggestion](https://user-images.githubusercontent.com/2473545/66421272-f2ad5200-e9dd-11e9-9fca-e3c5bdedb611.png)

**Comment by perragnar** [comment]
I used Remote Development for the first time today and I actually added this to my todo list. At first I was going to make it inverted to make it pop out a bit but I think I like your color suggestion better. A new version is beeing published as we speak..
