### ISSUE TITLE
Incorrect tokens coloring when using Rust Analyzer

### ISSUE THREAD

**Issue by proninyaroslav** [perragnar/light-plus-tweaked#9]
Hi. I use Light+ Tweaked Theme and Rust Analyzer to work with Rust projects. I noticed that when using the tweaked version, the syntax coloring for Rust is incomplete. I took a screenshot to compare with the default Light+, in which the tokens coloring is correct (method calls, variables, modules, enums). Is this a Rust Analyzer problem or is it a tweaked version problem? As far as I know, Rust Analyzer highlight tokens on its side.

Tweaked:
![Снимок экрана от 2020-05-26 17-56-21](https://user-images.githubusercontent.com/7840559/82916882-4ffd1000-9f7b-11ea-9962-ecce6dff5ec1.png)
Default:
![Снимок экрана от 2020-05-26 17-56-44](https://user-images.githubusercontent.com/7840559/82916885-5095a680-9f7b-11ea-87f5-a85ca8adef9b.png)

**Comment by perragnar** [comment]
I will take a look at this. I'm not sure but it might have something to do with the new semantic highlighting.

Thanks for reporting!

**Comment by perragnar** [comment]
Hey! Sorry for the delay in this issue.. I have updated the themes to the latest tokenColors from the default VSCode themes. I hope this update fixes the highlighting.

**Comment by proninyaroslav** [comment]
Yes, this is fixed. Thank you very much!

**Comment by proninyaroslav** [comment]
I'm sorry I was wrong. It seems this is not fixed.

**Comment by perragnar** [comment]
Hmm, I will check if there's something else that's different from the default theme.
Did you reload VSCode after updating the theme?

**Comment by proninyaroslav** [comment]
Yes

**Comment by zhibinr** [comment]
Why the `semanticHighlighting` part was remove from the tweak?

```json
"semanticHighlighting": true,
"semanticTokenColors": {
    "newOperator": "#AF00DB",
    "stringLiteral": "#a31515",
    "customLiteral": "#795E26",
    "numberLiteral": "#098658",
}
```
I think that's the reason.
